# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
$schema: moz://mozilla.org/schemas/glean/metrics/2-0-0

test:
  run:
    type: uuid
    description: >
      ID of the current test run.
    metadata:
      tags:
        - automation
    lifetime: application
    send_in_pings:
      - discovery
      - space-ship-ready
      - starbase46
      - deletion-request
    bugs:
      - https://github.com/mozilla/burnham/issues/5
    data_reviews:
      - https://bugzilla.mozilla.org/show_bug.cgi?id=1643412
    notification_emails:
      - raphael@mozilla.com
    expires: never

  name:
    type: string
    description: >
      Name of the current test.
    metadata:
      tags:
        - automation
    lifetime: application
    send_in_pings:
      - discovery
      - space-ship-ready
      - starbase46
      - deletion-request
    bugs:
      - https://github.com/mozilla/burnham/issues/5
    data_reviews:
      - https://bugzilla.mozilla.org/show_bug.cgi?id=1643412
    notification_emails:
      - raphael@mozilla.com
    expires: never

  airflow_task_id:
    type: string
    description: >
      ID of the Airflow task that runs the client
    metadata:
      tags:
        - automation
    lifetime: application
    send_in_pings:
      - discovery
      - space-ship-ready
      - starbase46
      - deletion-request
    bugs:
      - https://github.com/mozilla/burnham/issues/381
    data_reviews:
      - https://github.com/mozilla/burnham/pull/387
    notification_emails:
      - raphael@mozilla.com
    expires: never

technology:
  space_travel:
    type: labeled_counter
    description: >
      Counts the number of times a space-travel technology is used.
    metadata:
      tags:
        - science
    labels:
      - warp_drive
      - spore_drive
    send_in_pings:
      - discovery
    bugs:
      - https://github.com/mozilla/burnham/issues/5
    data_reviews:
      - https://bugzilla.mozilla.org/show_bug.cgi?id=1643412
    notification_emails:
      - raphael@mozilla.com
    expires: never

mission:
  identifier:
    type: string
    description: >
      The identifier of the current mission.
    metadata:
      tags:
        - science
    lifetime: application
    send_in_pings:
      - discovery
    bugs:
      - https://github.com/mozilla/burnham/issues/5
    data_reviews:
      - https://bugzilla.mozilla.org/show_bug.cgi?id=1643412
    notification_emails:
      - raphael@mozilla.com
    expires: never

  status:
    type: string
    description: >
      The status of the current mission.
    metadata:
      tags:
        - science
    lifetime: application
    send_in_pings:
      - discovery
    bugs:
      - https://github.com/mozilla/burnham/issues/5
    data_reviews:
      - https://bugzilla.mozilla.org/show_bug.cgi?id=1643412
    notification_emails:
      - raphael@mozilla.com
    expires: never
